<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="SqlParsing\Models\" />
    <Folder Include="SqlParsing\Querying\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
  </ItemGroup>

</Project>
